### ISSUE TITLE
Atividade 08 - Desafio de CSS

### ISSUE THREAD

**Issue by dev-brunosantos** [dev-alexandre2024/Mentoria-Dev#11]
## Ação

Nesse desafio iremos praticar as animações do tipo `hover`.
O intuito desse desafio é replicar exatamente o que esta acontecendo no exemplo abaixo.

https://github.com/user-attachments/assets/336fd787-51a5-4d22-b26a-a05068a2c15f

## Observação

- Para facilitar na resolução do desafio irei disponibilizar o codigo do HTML pronto e você terá a obrigação de criar apenas o arquivo CSS.

- Para iniciar o projeto com o HTML pronto, será necessário rodar os comandos de atualização do repositório:
```
git fetch
git pull origin main
```

- Ao rodar o comando de atualização irá aparecer a pasta referente a atividade 08 com o codigo CSS.

**Comment by dev-brunosantos** [comment]
# Observações 

### Em caso de duvidas, deverá ser consultado os codigos que já foram feitos nas outras atividades e tentar pegar algum padrão que ja foi criado

**Comment by dev-alexandre2024** [comment]
estou com dificuldade na questao da animaçao
por que ela esta mudando de lugar e eu não sei como fazer ela sumir e tambem nao conheço os codigos utilizados

**Comment by dev-brunosantos** [comment]
A intensão da tarefa é tentar encontrar codigos parecidos em atividades que você já realizou. 
A tarefa realmente é um desafio e por isso esta marcada como `  DIFICIL   `

### Dica 

Dá uma olhada na animação que vc criou nos itens do menu principal do site que estamos criando na `   TAREFA 07   `

**Comment by dev-alexandre2024** [comment]
dei uma olhada porem a animação que criei faz com que a div troque de lugar
e tambem usei 360deg na animação sera que é por isso

**Comment by dev-brunosantos** [comment]
Ta indo por um caminho que pode funcionar.
Porém, tenta fazer com que a ` div ` permaneça na mesmo local, sempre centralizado.
